# Animal encyclopedia data
# Each category includes at least 12 animals.

ANIMAL_CATEGORIES = {
    "mammals": {
        "name": {"en": "Mammals", "zh": "哺乳动物", "ko": "포유류"},
        "description": {
            "en": "Warm-blooded vertebrates that typically give live birth and nurse young.",
            "zh": "温血、胎生（大多）、哺乳的脊椎动物。",
            "ko": "대부분 새끼를 낳고 젖을 먹이는 온혈 척추동물.",
        }
    },
    "birds": {
        "name": {"en": "Birds", "zh": "鸟类", "ko": "조류"},
        "description": {
            "en": "Feathered, warm-blooded animals with beaks and lightweight skeletons.",
            "zh": "有羽毛、喙和轻骨骼的温血动物。",
            "ko": "깃털과 부리를 지닌 온혈 동물.",
        }
    },
    "reptiles": {
        "name": {"en": "Reptiles", "zh": "爬行动物", "ko": "파충류"},
        "description": {
            "en": "Cold-blooded vertebrates with scales, often laying eggs.",
            "zh": "冷血、有鳞片，常为卵生的脊椎动物。",
            "ko": "비늘을 가진 변온 척추동물로, 많은 종이 알을 낳습니다.",
        }
    },
    "amphibians": {
        "name": {"en": "Amphibians", "zh": "两栖动物", "ko": "양서류"},
        "description": {
            "en": "Animals that live part of their lives in water and part on land.",
            "zh": "水陆两栖、常经历变态发育。",
            "ko": "물과 육지에서 모두 생활하는 동물.",
        }
    },
    "fish": {
        "name": {"en": "Fish", "zh": "鱼类", "ko": "어류"},
        "description": {
            "en": "Aquatic vertebrates that typically breathe with gills.",
            "zh": "主要用鳃呼吸的水生脊椎动物。",
            "ko": "대개 아가미로 호흡하는 수생 척추동물.",
        }
    },
    "insects": {
        "name": {"en": "Insects", "zh": "昆虫", "ko": "곤충"},
        "description": {
            "en": "Arthropods with six legs and three body segments.",
            "zh": "六足、三段体、外骨骼的节肢动物。",
            "ko": "여섯 다리와 세 부분의 몸을 가진 절지동물.",
        }
    },
}

# Helper to keep entries compact
def _a(
    common_en, common_zh, common_ko,
    sci, category,
    summary_en, summary_zh, summary_ko,
    habitat_en, habitat_zh, habitat_ko,
    diet_en, diet_zh, diet_ko,
    facts_en, facts_zh=None, facts_ko=None
):
    return {
        "category": category,
        "common_name_en": common_en,
        "common_name_zh": common_zh,
        "common_name_ko": common_ko,
        "scientific_name": sci,
        "summary_en": summary_en,
        "summary_zh": summary_zh,
        "summary_ko": summary_ko,
        "habitat_en": habitat_en,
        "habitat_zh": habitat_zh,
        "habitat_ko": habitat_ko,
        "diet_en": diet_en,
        "diet_zh": diet_zh,
        "diet_ko": diet_ko,
        "fun_facts_en": facts_en,
        "fun_facts_zh": facts_zh or [],
        "fun_facts_ko": facts_ko or [],
    }

ANIMALS_DATA = {
    # ---------------- Mammals (12) ----------------
    "giant_panda": _a(
        "Giant Panda", "大熊猫", "자이언트판다",
        "Ailuropoda melanoleuca", "mammals",
        "A bamboo-specialist bear native to China.",
        "中国特有的以竹子为主食的熊类。",
        "중국 고유의 대나무를 주로 먹는 곰.",
        "Temperate mountain forests with bamboo.",
        "有竹林的温带山地森林。",
        "대나무가 있는 온대 산림.",
        "Mostly bamboo.",
        "主要吃竹子。",
        "주로 대나무.",
        ["They have a ‘pseudo-thumb’ for gripping bamboo."]
    ),
    "tiger": _a(
        "Tiger", "老虎", "호랑이",
        "Panthera tigris", "mammals",
        "The largest cat species and an apex predator in Asia.",
        "亚洲最大的猫科顶级掠食者。",
        "아시아의 최상위 포식자이자 가장 큰 고양잇과.",
        "Forests, grasslands, mangroves.",
        "森林、草原、红树林。",
        "숲, 초원, 맹그로브.",
        "Carnivorous; deer, boar, etc.",
        "肉食性，捕食鹿、野猪等。",
        "육식성.",
        ["Each tiger’s stripe pattern is unique."]
    ),
    "african_elephant": _a(
        "African Elephant", "非洲象", "아프리카코끼리",
        "Loxodonta africana", "mammals",
        "The largest land mammal with complex social behavior.",
        "陆地上体型最大的哺乳动物，社会性强。",
        "가장 큰 육상 포유류로 사회성이 높음.",
        "Savannas and forests in sub-Saharan Africa.",
        "撒哈拉以南非洲草原与森林。",
        "사하라 이남의 사바나와 숲.",
        "Herbivorous; grasses, leaves, bark.",
        "草食性。",
        "초식성.",
        ["Gestation lasts about 22 months."]
    ),
    "gray_wolf": _a(
        "Gray Wolf", "灰狼", "회색늑대",
        "Canis lupus", "mammals",
        "Highly social carnivore known for pack hunting.",
        "以群体协作捕猎著称的社会性食肉动物。",
        "무리 사냥으로 유명한 사회적 육식동물.",
        "Forests, tundra, grasslands.",
        "森林、苔原、草原。",
        "숲, 툰드라, 초원.",
        "Carnivorous; ungulates and small mammals.",
        "肉食性。",
        "육식성.",
        ["Howls help coordinate pack members over long distances."]
    ),
    "polar_bear": _a(
        "Polar Bear", "北极熊", "북극곰",
        "Ursus maritimus", "mammals",
        "A marine-adapted bear dependent on sea ice.",
        "高度依赖海冰的海洋型熊类。",
        "해빙에 의존하는 해양 적응 곰.",
        "Arctic sea ice and coastal areas.",
        "北极海冰与沿岸地区。",
        "북극 해빙과 연안.",
        "Carnivorous; seals mainly.",
        "主要捕食海豹。",
        "주로 물개.",
        ["Their fur is translucent; skin is black."]
    ),
    "red_fox": _a(
        "Red Fox", "赤狐", "붉은여우",
        "Vulpes vulpes", "mammals",
        "An adaptable omnivore found across the Northern Hemisphere.",
        "适应力极强的杂食动物。",
        "적응력이 뛰어난 잡식성 여우.",
        "Forests, farmlands, cities.",
        "森林、农田、城市。",
        "숲, 농경지, 도시.",
        "Omnivorous; rodents, birds, fruits.",
        "杂食性。",
        "잡식성.",
        ["They can hear small animals moving under snow."]
    ),
    "koala": _a(
        "Koala", "考拉", "코알라",
        "Phascolarctos cinereus", "mammals",
        "An Australian marsupial specializing in eucalyptus leaves.",
        "澳大利亚特有的桉树叶专食有袋类。",
        "유칼립투스 잎을 먹는 호주 유대류.",
        "Eucalyptus woodlands.",
        "桉树林。",
        "유칼립투스 숲.",
        "Mostly eucalyptus leaves.",
        "主要吃桉树叶。",
        "주로 유칼립투스 잎.",
        ["They sleep up to 18–20 hours a day."]
    ),
    "kangaroo": _a(
        "Red Kangaroo", "红大袋鼠", "붉은캥거루",
        "Osphranter rufus", "mammals",
        "The largest marsupial, adapted to arid Australia.",
        "最大型有袋类，适应澳洲干旱环境。",
        "건조한 호주에 적응한 가장 큰 유대류.",
        "Arid and semi-arid plains.",
        "干旱与半干旱平原。",
        "건조 및 반건조 평원.",
        "Herbivorous; grasses and shrubs.",
        "草食性。",
        "초식성.",
        ["Powerful hind legs enable long-distance hopping."]
    ),
    "bottlenose_dolphin": _a(
        "Bottlenose Dolphin", "宽吻海豚", "큰돌고래",
        "Tursiops truncatus", "mammals",
        "Intelligent marine mammal noted for echolocation.",
        "以回声定位和高智力著称的海洋哺乳动物。",
        "반향정위로 유명한 지능 높은 해양 포유류.",
        "Coastal and offshore warm-temperate seas.",
        "温带至热带沿海与外海。",
        "온대~열대 연안 및 외해.",
        "Carnivorous; fish and squid.",
        "肉食性。",
        "육식성.",
        ["They use signature whistles to identify individuals."]
    ),
    "cheetah": _a(
        "Cheetah", "猎豹", "치타",
        "Acinonyx jubatus", "mammals",
        "The fastest land animal, built for sprinting.",
        "陆地上速度最快的动物。",
        "지상에서 가장 빠른 동물.",
        "African savannas and open habitats.",
        "非洲草原等开阔地带。",
        "아프리카 사바나.",
        "Carnivorous; gazelles and small antelopes.",
        "肉食性。",
        "육식성.",
        ["Top speed can exceed 90 km/h in short bursts."]
    ),
    "orangutan": _a(
        "Orangutan", "红毛猩猩", "오랑우탄",
        "Pongo spp.", "mammals",
        "Great apes known for arboreal life and tool use.",
        "以树栖生活和使用工具著称的大型类人猿。",
        "나무 위 생활과 도구 사용으로 유명한 유인원.",
        "Rainforests of Borneo and Sumatra.",
        "婆罗洲与苏门答腊雨林。",
        "보르네오·수마트라 열대우림.",
        "Primarily fruit, also leaves and insects.",
        "以果实为主。",
        "주로 과일.",
        ["They build a new sleeping nest almost every night."]
    ),
    "platypus": _a(
        "Platypus", "鸭嘴兽", "오리너구리",
        "Ornithorhynchus anatinus", "mammals",
        "A unique egg-laying mammal from Australia.",
        "非常独特的卵生哺乳动物。",
        "알을 낳는 독특한 포유류.",
        "Freshwater rivers and lakes in eastern Australia.",
        "澳大利亚东部淡水水域。",
        "호주 동부 담수.",
        "Aquatic invertebrates.",
        "水生无脊椎动物。",
        "수서 무척추동물.",
        ["Males have venomous spurs on their hind legs."]
    ),

    # ---------------- Birds (12) ----------------
    "bald_eagle": _a(
        "Bald Eagle", "白头海雕", "흰머리수리",
        "Haliaeetus leucocephalus", "birds",
        "A large raptor associated with North American coasts and lakes.",
        "北美沿海与湖区的大型猛禽。",
        "북미의 대표적인 대형 맹금.",
        "Near rivers, lakes, and coasts.",
        "河流、湖泊、海岸附近。",
        "강·호수·해안.",
        "Fish and waterfowl.",
        "以鱼类为主。",
        "주로 물고기.",
        ["Builds massive nests used for years."]
    ),
    "golden_eagle": _a(
        "Golden Eagle", "金雕", "검독수리",
        "Aquila chrysaetos", "birds",
        "A powerful hunter with broad distribution in the Northern Hemisphere.",
        "北半球分布广、捕猎能力强的猛禽。",
        "북반구에 널리 분포한 강력한 사냥꾼.",
        "Mountains and open landscapes.",
        "山地与开阔地区。",
        "산악 및 개활지.",
        "Rabbits, marmots, birds.",
        "肉食性。",
        "육식성.",
        ["Exceptional eyesight for long-range spotting."]
    ),
    "emperor_penguin": _a(
        "Emperor Penguin", "帝企鹅", "황제펭귄",
        "Aptenodytes forsteri", "birds",
        "The largest penguin, breeding through Antarctic winters.",
        "体型最大的企鹅，能在南极严冬繁殖。",
        "가장 큰 펭귄으로 남극 겨울에 번식.",
        "Antarctic ice and surrounding seas.",
        "南极冰架与海域。",
        "남극 해빙과 바다.",
        "Fish, squid, krill.",
        "鱼类、鱿鱼、磷虾。",
        "물고기, 오징어, 크릴.",
        ["Males incubate eggs on their feet."]
    ),
    "barn_owl": _a(
        "Barn Owl", "仓鸮", "가면올빼미",
        "Tyto alba", "birds",
        "A nocturnal hunter with a heart-shaped face.",
        "以心形脸盘著名的夜行猛禽。",
        "하트 모양 얼굴의 야행성 맹금.",
        "Farmlands, grasslands, open woods.",
        "农田、草原、林缘。",
        "농경지, 초원.",
        "Rodents mainly.",
        "主要捕食鼠类。",
        "주로 설치류.",
        ["Silent flight helps surprise prey."]
    ),
    "peacock": _a(
        "Indian Peafowl", "孔雀", "공작",
        "Pavo cristatus", "birds",
        "Known for the male’s spectacular tail display.",
        "雄鸟拥有华丽的开屏尾羽。",
        "수컷의 화려한 꼬리가 특징.",
        "Forests and human-adjacent habitats in South Asia.",
        "南亚森林及人类活动区附近。",
        "남아시아 숲.",
        "Omnivorous; seeds, insects, small animals.",
        "杂食性。",
        "잡식성.",
        ["Tail feathers are used in courtship displays."]
    ),
    "flamingo": _a(
        "Greater Flamingo", "大红鹳", "큰홍학",
        "Phoenicopterus roseus", "birds",
        "Pink wading bird feeding in shallow saline lakes.",
        "在浅盐湖觅食的粉色涉禽。",
        "얕은 염호에서 먹이를 찾는 분홍색 새.",
        "Shallow lakes and lagoons.",
        "浅湖与潟湖。",
        "얕은 호수와 석호.",
        "Algae and small crustaceans.",
        "藻类与小型甲壳类。",
        "조류와 작은 갑각류.",
        ["Pink color comes from carotenoids in diet."]
    ),
    "hummingbird": _a(
        "Ruby-throated Hummingbird", "红喉蜂鸟", "루비목벌새",
        "Archilochus colubris", "birds",
        "A tiny bird capable of hovering flight.",
        "能悬停飞行的微型鸟类。",
        "공중 정지가 가능한 작은 새.",
        "Gardens and wood edges in the Americas.",
        "美洲的花园与林缘。",
        "아메리카의 정원.",
        "Nectar and small insects.",
        "花蜜与小昆虫。",
        "꽃꿀과 곤충.",
        ["Beats wings dozens of times per second."]
    ),
    "ostrich": _a(
        "Ostrich", "鸵鸟", "타조",
        "Struthio camelus", "birds",
        "The largest living bird, adapted for running.",
        "现存最大鸟类，善于奔跑。",
        "달리기에 특화된 가장 큰 새.",
        "African savannas and semi-deserts.",
        "非洲草原与半荒漠。",
        "아프리카 사바나.",
        "Omnivorous; plants, insects.",
        "杂食性。",
        "잡식성.",
        ["Can run around 70 km/h."]
    ),
    "swan": _a(
        "Mute Swan", "疣鼻天鹅", "혹고니",
        "Cygnus olor", "birds",
        "Large waterfowl often seen on lakes and slow rivers.",
        "常见于湖泊与缓流河道的大型水禽。",
        "호수에서 흔히 보이는 대형 물새.",
        "Lakes, ponds, slow rivers.",
        "湖泊、池塘、缓流。",
        "호수, 연못.",
        "Aquatic plants.",
        "水生植物为主。",
        "수생 식물.",
        ["Forms strong pair bonds."]
    ),
    "macaw": _a(
        "Blue-and-yellow Macaw", "黄蓝金刚鹦鹉", "청황금강앵무",
        "Ara ararauna", "birds",
        "A colorful parrot from South American rainforests.",
        "南美雨林的综合色彩鹦鹉。",
        "남미 열대우림의 화려한 앵무.",
        "Tropical forests.",
        "热带森林。",
        "열대 숲.",
        "Fruits, nuts, seeds.",
        "果实、坚果、种子。",
        "과일, 견과.",
        ["Highly intelligent and social."]
    ),
    "albatross": _a(
        "Wandering Albatross", "漂泊信天翁", "방랑알바트로스",
        "Diomedea exulans", "birds",
        "A seabird with one of the largest wingspans.",
        "翼展极大的远洋海鸟。",
        "가장 큰 날개폭을 가진 바닷새 중 하나.",
        "Southern Ocean.",
        "南大洋。",
        "남극해 인근.",
        "Fish, squid, carrion.",
        "鱼类、鱿鱼等。",
        "물고기, 오징어.",
        ["Can glide for hours with minimal flapping."]
    ),
    "woodpecker": _a(
        "Great Spotted Woodpecker", "大斑啄木鸟", "오색딱따구리",
        "Dendrocopos major", "birds",
        "A forest bird known for drumming on trees.",
        "以啄木和敲击树干著称。",
        "나무를 두드리는 습성이 유명.",
        "Woodlands and parks.",
        "林地与公园。",
        "숲과 공원.",
        "Insects, seeds, nuts.",
        "昆虫及植物性食物。",
        "곤충과 씨앗.",
        ["Shock-absorbing skull helps prevent injury."]
    ),

    # ---------------- Reptiles (12) ----------------
    "nile_crocodile": _a(
        "Nile Crocodile", "尼罗鳄", "나일악어",
        "Crocodylus niloticus", "reptiles",
        "A large African crocodile and an apex aquatic predator.",
        "非洲大型鳄鱼之一。",
        "아프리카의 대형 악어.",
        "Rivers, lakes, wetlands.",
        "河流、湖泊、湿地。",
        "강, 호수, 습지.",
        "Fish, birds, mammals.",
        "肉食性。",
        "육식성.",
        ["Can remain motionless for long ambushes."]
    ),
    "komodo_dragon": _a(
        "Komodo Dragon", "科莫多巨蜥", "코모도왕도마뱀",
        "Varanus komodoensis", "reptiles",
        "The largest living lizard, endemic to Indonesian islands.",
        "现存最大蜥蜴。",
        "현존 최대 도마뱀.",
        "Dry forests and savannas on Komodo islands.",
        "印尼部分岛屿。",
        "인도네시아 일부 섬.",
        "Carnivorous; deer, boar, carrion.",
        "肉食性。",
        "육식성.",
        ["Has venom glands aiding in hunting."]
    ),
    "green_iguana": _a(
        "Green Iguana", "绿鬣蜥", "그린이구아나",
        "Iguana iguana", "reptiles",
        "A large arboreal lizard common in the Americas.",
        "美洲常见的大型树栖蜥蜴。",
        "아메리카의 대형 수목성 도마뱀.",
        "Tropical forests near water.",
        "热带森林。",
        "열대 숲.",
        "Mostly herbivorous.",
        "以植物为主。",
        "주로 초식.",
        ["Excellent swimmers."]
    ),
    "king_cobra": _a(
        "King Cobra", "眼镜王蛇", "킹코브라",
        "Ophiophagus hannah", "reptiles",
        "The longest venomous snake, specializing in other snakes.",
        "世界上最长的毒蛇。",
        "가장 긴 독사.",
        "Forests in South and Southeast Asia.",
        "南亚、东南亚森林。",
        "남·동남아 숲.",
        "Carnivorous; snakes mainly.",
        "以蛇为主食。",
        "주로 다른 뱀.",
        ["Builds nests for eggs."]
    ),
    "ball_python": _a(
        "Ball Python", "球蟒", "볼파이톤",
        "Python regius", "reptiles",
        "A docile constrictor often kept as a pet.",
        "较温顺的缠绕型蛇类。",
        "비교적 온순한 비단뱀.",
        "Grasslands and forests of West Africa.",
        "西非草原与森林。",
        "서아프리카.",
        "Rodents and small birds.",
        "小型哺乳动物等。",
        "설치류.",
        ["Curls into a tight ball when threatened."]
    ),
    "sea_turtle": _a(
        "Green Sea Turtle", "绿海龟", "푸른바다거북",
        "Chelonia mydas", "reptiles",
        "A large sea turtle that grazes on seagrass as adults.",
        "成体以海草为主食的大型海龟。",
        "성체는 해초를 먹는 대형 바다거북.",
        "Tropical and subtropical oceans.",
        "热带与亚热带海域。",
        "열대 바다.",
        "Adults mostly herbivorous.",
        "成体偏草食。",
        "성체는 초식성 경향.",
        ["Returns to natal beaches to lay eggs."]
    ),
    "gharials": _a(
        "Gharial", "恒河鳄", "가비알",
        "Gavialis gangeticus", "reptiles",
        "A fish-eating crocodilian with a long narrow snout.",
        "以细长吻部著称的食鱼鳄类。",
        "가늘고 긴 주둥이의 어식성 악어.",
        "Large rivers in the Indian subcontinent.",
        "印度次大陆大河。",
        "인도 아대륙의 큰 강.",
        "Fish.",
        "主要吃鱼。",
        "물고기.",
        ["Critically adapted for catching fish efficiently."]
    ),
    "chameleon": _a(
        "Veiled Chameleon", "高冠变色龙", "베일드카멜레온",
        "Chamaeleo calyptratus", "reptiles",
        "A tree-dwelling lizard known for color changes.",
        "以变色和树栖生活著称。",
        "색 변화로 유명한 수목성 도마뱀.",
        "Dry forests and shrublands.",
        "灌丛与林地。",
        "관목지.",
        "Insects mainly.",
        "昆虫为主。",
        "곤충.",
        ["Color change is more about mood and signaling than camouflage."]
    ),
    "gecko": _a(
        "Tokay Gecko", "蛤蚧", "토케이도마뱀붙이",
        "Gekko gecko", "reptiles",
        "A large gecko with loud territorial calls.",
        "叫声响亮的大型壁虎。",
        "큰 몸집과 큰 울음소리의 도마뱀붙이.",
        "Tropical forests and human dwellings.",
        "热带森林及人类居住区。",
        "열대 숲.",
        "Insects and small vertebrates.",
        "昆虫等。",
        "곤충.",
        ["Exceptional climbing ability due to toe pads."]
    ),
    "rattlesnake": _a(
        "Western Diamondback Rattlesnake", "西部菱背响尾蛇", "서부다이아몬드백방울뱀",
        "Crotalus atrox", "reptiles",
        "A venomous snake known for its warning rattle.",
        "以尾端警示性响声著称的毒蛇。",
        "꼬리 방울로 경고하는 독사.",
        "Deserts and scrublands of the U.S. Southwest.",
        "北美西南部荒漠。",
        "미국 남서부 사막.",
        "Rodents.",
        "鼠类为主。",
        "설치류.",
        ["Rattle helps avoid unnecessary conflicts."]
    ),
    "anaconda": _a(
        "Green Anaconda", "绿森蚺", "그린아나콘다",
        "Eunectes murinus", "reptiles",
        "One of the heaviest snakes, semi-aquatic.",
        "体重最大的蛇之一。",
        "가장 무거운 뱀 중 하나.",
        "Swamps and slow rivers of South America.",
        "南美沼泽与缓流河。",
        "남미 습지.",
        "Fish, birds, mammals.",
        "肉食性。",
        "육식성.",
        ["Females are much larger than males."]
    ),

    # ---------------- Amphibians (12) ----------------
    "red_eyed_tree_frog": _a(
        "Red-eyed Tree Frog", "红眼树蛙", "붉은눈청개구리",
        "Agalychnis callidryas", "amphibians",
        "A colorful rainforest frog from Central America.",
        "中美洲雨林的标志性树蛙。",
        "중미 열대우림의 대표적 개구리.",
        "Tropical rainforests near water.",
        "热带雨林。",
        "열대우림.",
        "Insects.",
        "昆虫。",
        "곤충.",
        ["Bright colors can startle predators."]
    ),
    "axolotl": _a(
        "Axolotl", "美西螈", "아홀로틀",
        "Ambystoma mexicanum", "amphibians",
        "A neotenic salamander that retains larval traits as an adult.",
        "成体仍保留幼体特征的蝾螈。",
        "성체가 유생 특징을 유지하는 도롱뇽.",
        "Freshwater lakes and canals.",
        "淡水湖泊与运河。",
        "담수.",
        "Worms, small fish, invertebrates.",
        "小型水生动物。",
        "수서 무척추동물.",
        ["Famous for remarkable regeneration abilities."]
    ),
    "poison_dart_frog": _a(
        "Strawberry Poison Dart Frog", "草莓箭毒蛙", "딸기독개구리",
        "Oophaga pumilio", "amphibians",
        "Small frog known for vivid warning colors.",
        "以鲜艳警戒色著称的小型蛙类。",
        "선명한 경고색의 작은 개구리.",
        "Tropical lowland forests.",
        "热带低地森林。",
        "열대 숲.",
        "Ants and small insects.",
        "蚂蚁等小昆虫。",
        "개미 등.",
        ["Toxins come from their diet in the wild."]
    ),
    "bullfrog": _a(
        "American Bullfrog", "美洲牛蛙", "황소개구리",
        "Lithobates catesbeianus", "amphibians",
        "A large frog with a deep booming call.",
        "体型大、鸣声洪亮。",
        "큰 몸집과 굵은 울음소리.",
        "Ponds, lakes, marshes.",
        "池塘、湖泊、沼泽。",
        "연못, 호수.",
        "Insects, fish, small animals.",
        "杂食偏肉食。",
        "곤충·작은 동물.",
        ["Can be invasive outside its native range."]
    ),
    "common_toad": _a(
        "Common Toad", "普通蟾蜍", "두꺼비",
        "Bufo bufo", "amphibians",
        "A widespread toad adapted to many habitats.",
        "分布广、适应力强的蟾蜍。",
        "넓게 분포하는 두꺼비.",
        "Woodlands, gardens, farmlands.",
        "林地、花园、农田。",
        "숲, 정원.",
        "Insects and worms.",
        "昆虫、蚯蚓等。",
        "곤충.",
        ["Produces mild toxins to deter predators."]
    ),
    "salamander_fire": _a(
        "Fire Salamander", "火蝾螈", "불도롱뇽",
        "Salamandra salamandra", "amphibians",
        "Black-and-yellow salamander living in moist forests.",
        "生活在潮湿森林的黑黄相间蝾螈。",
        "습한 숲의 검정-노랑 도롱뇽.",
        "Moist temperate forests.",
        "潮湿温带森林。",
        "습한 온대 숲.",
        "Invertebrates.",
        "无脊椎动物。",
        "무척추동물.",
        ["Secretes toxins from skin glands."]
    ),
    "newt": _a(
        "Eastern Newt", "东部蝾螈", "동부영원",
        "Notophthalmus viridescens", "amphibians",
        "A newt with distinct life stages including a terrestrial juvenile phase.",
        "生命周期阶段明显的蝾螈。",
        "여러 생활사를 갖는 영원.",
        "Ponds and nearby forests in eastern North America.",
        "北美东部池塘及周边林地。",
        "북미 동부.",
        "Small invertebrates.",
        "小型无脊椎动物。",
        "작은 무척추동물.",
        ["Juveniles are bright orange, warning predators."]
    ),
    "glass_frog": _a(
        "Glass Frog", "玻璃蛙", "유리개구리",
        "Centrolenidae spp.", "amphibians",
        "Frogs with translucent bellies that reveal internal organs.",
        "腹部半透明的树蛙类群。",
        "배가 투명한 개구리류.",
        "Cloud forests near streams.",
        "云雾林溪流附近。",
        "운무림.",
        "Insects.",
        "昆虫。",
        "곤충.",
        ["Transparency may help camouflage."]
    ),
    "mudpuppy": _a(
        "Mudpuppy", "泥狗螈", "머드퍼피",
        "Necturus maculosus", "amphibians",
        "An aquatic salamander retaining external gills.",
        "终生水生、保留外鳃。",
        "외부 아가미를 유지하는 수생 도롱뇽.",
        "Lakes and rivers in North America.",
        "北美湖泊与河流。",
        "북미 담수.",
        "Crayfish, insects, fish eggs.",
        "甲壳类等。",
        "갑각류 등.",
        ["Active mostly at night."]
    ),
    "caecilian": _a(
        "Caecilian", "蚓螈", "무족양서류",
        "Gymnophiona spp.", "amphibians",
        "Legless burrowing amphibians resembling earthworms.",
        "形似蚯蚓、善于掘洞的无足两栖类。",
        "다리가 없는 굴파는 양서류.",
        "Tropical soils.",
        "热带土壤中。",
        "열대 토양.",
        "Worms and small invertebrates.",
        "小型无脊椎动物。",
        "작은 무척추동물.",
        ["Many people never see them due to underground life."]
    ),
    "wood_frog": _a(
        "Wood Frog", "林蛙", "숲개구리",
        "Lithobates sylvaticus", "amphibians",
        "A frog famous for surviving partial freezing.",
        "能耐受部分体液冻结的蛙类。",
        "부분 동결을 견디는 개구리.",
        "Boreal forests in North America.",
        "北美寒温带森林。",
        "북미의 한대 숲.",
        "Insects.",
        "昆虫。",
        "곤충.",
        ["Can survive winter by freezing and thawing."]
    ),
    "giant_salamander": _a(
        "Chinese Giant Salamander", "中国大鲵", "중국대왕도롱뇽",
        "Andrias davidianus", "amphibians",
        "One of the largest amphibians in the world.",
        "世界最大两栖动物之一。",
        "세계에서 가장 큰 양서류 중 하나.",
        "Cool, fast-flowing mountain streams.",
        "山地冷水急流。",
        "차갑고 빠른 산악 하천.",
        "Fish and aquatic invertebrates.",
        "鱼类等。",
        "물고기 등.",
        ["Often called a 'living fossil'."]
    ),

    # ---------------- Fish (12) ----------------
    "great_white_shark": _a(
        "Great White Shark", "大白鲨", "백상아리",
        "Carcharodon carcharias", "fish",
        "A large predatory shark found in coastal temperate seas.",
        "沿海温带海域的大型掠食鲨。",
        "연안 온대 바다의 대형 포식 상어.",
        "Coastal temperate oceans.",
        "温带沿海海域。",
        "온대 연안.",
        "Seals, fish.",
        "海豹、鱼类。",
        "물고기·물개.",
        ["Highly sensitive electroreception helps locate prey."]
    ),
    "clownfish": _a(
        "Clownfish", "小丑鱼", "흰동가리",
        "Amphiprioninae spp.", "fish",
        "Reef fish living symbiotically with sea anemones.",
        "与海葵共生的珊瑚礁鱼类。",
        "말미잘과 공생하는 산호초 물고기.",
        "Coral reefs.",
        "珊瑚礁。",
        "산호초.",
        "Omnivorous; algae and small invertebrates.",
        "杂食性。",
        "잡식성.",
        ["They are immune to anemone stings via mucus adaptation."]
    ),
    "bluefin_tuna": _a(
        "Atlantic Bluefin Tuna", "大西洋蓝鳍金枪鱼", "대서양참다랑어",
        "Thunnus thynnus", "fish",
        "A fast, warm-bodied tuna prized in fisheries.",
        "高速游泳、经济价值高的金枪鱼。",
        "빠른 속도의 참치.",
        "Open ocean.",
        "远洋。",
        "원양.",
        "Fish and squid.",
        "鱼类、鱿鱼。",
        "물고기·오징어.",
        ["Can maintain body temperature above surrounding water."]
    ),
    "seahorse": _a(
        "Seahorse", "海马", "해마",
        "Hippocampus spp.", "fish",
        "Small fish with upright posture and curled tails.",
        "直立游姿、尾巴可缠绕的鱼类。",
        "꼬리로 물체를 감는 작은 물고기.",
        "Seagrass beds and shallow reefs.",
        "海草床与浅海礁区。",
        "해초지.",
        "Small crustaceans.",
        "小型甲壳类。",
        "작은 갑각류.",
        ["Males carry and give birth to young."]
    ),
    "piranha": _a(
        "Red-bellied Piranha", "红腹食人鱼", "레드벨리피라냐",
        "Pygocentrus nattereri", "fish",
        "A freshwater fish with strong jaws, often misunderstood.",
        "以强壮颌部著称的淡水鱼。",
        "강한 턱을 가진 담수어.",
        "Amazon basin rivers.",
        "亚马逊流域。",
        "아마존 강.",
        "Fish, insects, carrion.",
        "杂食偏肉食。",
        "잡식성.",
        ["Most species are not aggressive toward humans."]
    ),
    "goldfish": _a(
        "Goldfish", "金鱼", "금붕어",
        "Carassius auratus", "fish",
        "A domesticated carp variety popular in aquariums.",
        "常见观赏鱼。",
        "대표적인 관상어.",
        "Ponds and aquariums.",
        "池塘与水族箱。",
        "연못·수조.",
        "Omnivorous.",
        "杂食性。",
        "잡식성.",
        ["Selective breeding produced many body and fin forms."]
    ),
    "koi": _a(
        "Koi", "锦鲤", "니시키고이",
        "Cyprinus rubrofuscus", "fish",
        "Ornamental carp symbolizing luck in East Asia.",
        "东亚文化中象征吉祥的观赏鲤。",
        "동아시아에서 상징성이 큰 관상 잉어.",
        "Ponds.",
        "池塘。",
        "연못.",
        "Omnivorous.",
        "杂食性。",
        "잡식성.",
        ["Can live for decades with good care."]
    ),
    "lionfish": _a(
        "Lionfish", "狮子鱼", "쏠배감펭",
        "Pterois volitans", "fish",
        "A venomous reef fish with dramatic fin spines.",
        "背鳍有毒、外形华丽的礁鱼。",
        "독가시가 있는 산호초 물고기.",
        "Indo-Pacific reefs; invasive in Atlantic.",
        "印太珊瑚礁；部分海域为入侵种。",
        "산호초.",
        "Small fish and crustaceans.",
        "小鱼、甲壳类。",
        "작은 물고기.",
        ["Invasive populations harm local reef ecosystems."]
    ),
    "manta_ray": _a(
        "Manta Ray", "蝠鲼", "만타가오리",
        "Mobula birostris", "fish",
        "Large gentle ray feeding on plankton.",
        "体型巨大、以浮游生物为食的温和鳐类。",
        "플랑크톤을 먹는 거대한 가오리.",
        "Open oceans and coastal upwellings.",
        "远洋与沿海上升流海域。",
        "원양.",
        "Plankton.",
        "浮游生物。",
        "플랑크톤.",
        ["Some individuals show curious interactions with divers."]
    ),
    "eel": _a(
        "European Eel", "欧洲鳗鲡", "유럽장어",
        "Anguilla anguilla", "fish",
        "A migratory fish with a mysterious life cycle.",
        "生命周期与洄游路线极具神秘色彩。",
        "신비로운 생활사를 가진 회유성 어류.",
        "Rivers and coastal waters; spawns in the Sargasso Sea.",
        "河流与沿海；在马尾藻海产卵。",
        "강과 연안.",
        "Invertebrates and small fish.",
        "小型水生动物。",
        "무척추동물 등.",
        ["Travel thousands of kilometers to spawn."]
    ),
    "anglerfish": _a(
        "Deep-sea Anglerfish", "深海鮟鱇鱼", "심해아귀",
        "Lophiiformes spp.", "fish",
        "Deep-sea fish using a luminous lure to attract prey.",
        "利用发光诱饵捕食的深海鱼。",
        "발광 미끼로 먹이를 유인하는 심해어.",
        "Deep ocean.",
        "深海。",
        "심해.",
        "Carnivorous.",
        "肉食性。",
        "육식성.",
        ["Extreme sexual dimorphism in many species."]
    ),
    "arowana": _a(
        "Asian Arowana", "亚洲龙鱼", "아시아아로와나",
        "Scleropages formosus", "fish",
        "A prized freshwater fish with ancient lineage.",
        "具有“活化石”气质的珍贵淡水鱼。",
        "고대 계통의 귀한 담수어.",
        "Slow rivers and swamps in Southeast Asia.",
        "东南亚缓流与沼泽。",
        "동남아.",
        "Small fish and insects.",
        "小鱼、昆虫。",
        "작은 물고기.",
        ["Highly valued in ornamental fish trade."]
    ),

    # ---------------- Insects (12) ----------------
    "monarch_butterfly": _a(
        "Monarch Butterfly", "帝王蝶", "왕나비",
        "Danaus plexippus", "insects",
        "Famous for long-distance migration in North America.",
        "以跨大陆迁徙闻名。",
        "장거리 이동으로 유명.",
        "Meadows, fields, gardens.",
        "草地、田野、花园。",
        "초원.",
        "Larvae eat milkweed; adults drink nectar.",
        "幼虫吃乳草，成虫吸蜜。",
        "유생은 밀크위드.",
        ["Migration can span thousands of kilometers."]
    ),
    "honey_bee": _a(
        "Western Honey Bee", "西方蜜蜂", "서양꿀벌",
        "Apis mellifera", "insects",
        "A key pollinator with complex hive societies.",
        "重要授粉昆虫，社会结构复杂。",
        "중요한 수분 곤충.",
        "Managed hives and diverse habitats.",
        "蜂箱与多种自然环境。",
        "다양한 환경.",
        "Nectar and pollen.",
        "花蜜与花粉。",
        "꽃꿀·꽃가루.",
        ["Waggle dance communicates food location."]
    ),
    "ladybug": _a(
        "Seven-spotted Ladybug", "七星瓢虫", "칠성무당벌레",
        "Coccinella septempunctata", "insects",
        "A beneficial beetle that eats aphids.",
        "以捕食蚜虫著称的益虫。",
        "진딧물을 먹는 익충.",
        "Fields, gardens, forests.",
        "田野、花园、森林。",
        "정원.",
        "Aphids and other small insects.",
        "蚜虫等。",
        "진딧물 등.",
        ["Bright colors warn predators of bitter taste."]
    ),
    "dragonfly": _a(
        "Emperor Dragonfly", "蓝蜻蜓", "왕잠자리",
        "Anax imperator", "insects",
        "A fast aerial predator around freshwater.",
        "淡水附近的高速空中捕食者。",
        "담수 근처의 공중 포식자.",
        "Lakes, ponds, slow rivers.",
        "湖泊、池塘、缓流。",
        "호수.",
        "Insects.",
        "昆虫。",
        "곤충.",
        ["Nymphs are aquatic and also predatory."]
    ),
    "mantis": _a(
        "Praying Mantis", "螳螂", "사마귀",
        "Mantodea spp.", "insects",
        "Camouflaged ambush predator with raptorial forelegs.",
        "擅长伏击捕猎的昆虫。",
        "매복 사냥에 특화.",
        "Gardens, grasslands, forests.",
        "花园、草地、林地。",
        "정원·초원.",
        "Insects and occasional small vertebrates.",
        "肉食性。",
        "육식성.",
        ["Females may eat males after mating in some species."]
    ),
    "stag_beetle": _a(
        "Stag Beetle", "锹形虫", "사슴벌레",
        "Lucanidae spp.", "insects",
        "Beetles with enlarged mandibles in males.",
        "雄虫具有夸张大颚。",
        "수컷의 큰 턱이 특징.",
        "Woodlands.",
        "林地。",
        "숲.",
        "Sap, rotting wood.",
        "树汁与腐木。",
        "수액.",
        ["Larvae can take years to mature."]
    ),
    "silkworm": _a(
        "Silkworm", "家蚕", "누에",
        "Bombyx mori", "insects",
        "A domesticated moth larva used for silk production.",
        "被人类驯化用于产丝。",
        "비단 생산에 이용되는 가정화 곤충.",
        "Human-managed environments.",
        "人工饲养环境。",
        "사육 환경.",
        "Mulberry leaves.",
        "桑叶。",
        "뽕잎.",
        ["Cannot survive well without human care."]
    ),
    "firefly": _a(
        "Firefly", "萤火虫", "반딧불이",
        "Lampyridae spp.", "insects",
        "Bioluminescent beetles used in mate signaling.",
        "会发光的甲虫类群。",
        "발광하는 딱정벌레.",
        "Moist fields, forests, riverbanks.",
        "湿润草地、林地、水边。",
        "습한 지역.",
        "Larvae eat snails and small invertebrates.",
        "幼虫捕食小型无脊椎动物。",
        "유충은 달팽이 등.",
        ["Light patterns help species recognize mates."]
    ),
    "ant": _a(
        "Leafcutter Ant", "切叶蚁", "잎꾼개미",
        "Atta spp.", "insects",
        "Farms fungus using freshly cut leaves.",
        "用叶片培育真菌的“农业”昆虫。",
        "잎으로 곰팡이를 재배.",
        "Tropical forests of the Americas.",
        "美洲热带森林。",
        "열대 숲.",
        "Fungus cultivated from leaves.",
        "以真菌为食。",
        "재배한 균류.",
        ["Complex division of labor in colonies."]
    ),
    "termite": _a(
        "Termite", "白蚁", "흰개미",
        "Isoptera (infraorder)", "insects",
        "Social insects that decompose wood and plant matter.",
        "能分解木质纤维的社会性昆虫。",
        "목재 분해에 중요한 사회성 곤충.",
        "Tropical and temperate regions.",
        "热带与温带。",
        "열대·온대.",
        "Cellulose with microbial help.",
        "在微生物帮助下消化纤维素。",
        "셀룰로오스.",
        ["Build elaborate mounds and tunnels."]
    ),
    "mosquito": _a(
        "Mosquito", "蚊子", "모기",
        "Culicidae spp.", "insects",
        "Small flies; only females of many species bite for blood.",
        "雌蚊吸血以促产卵。",
        "여러 종에서 암컷만 흡혈.",
        "Near standing water.",
        "积水附近。",
        "고인 물 주변.",
        "Nectar; females may also need blood.",
        "花蜜；雌蚊可能吸血。",
        "꽃꿀.",
        ["Major vectors for several diseases."]
    ),
    "grasshopper": _a(
        "Grasshopper", "蝗虫/蚱蜢", "메뚜기",
        "Acrididae spp.", "insects",
        "Plant-eating insects capable of mass swarming in some species.",
        "部分种类可形成大规模群聚。",
        "일부 종은 대군집 발생.",
        "Grasslands and farmlands.",
        "草原与农田。",
        "초원·농경지.",
        "Herbivorous.",
        "草食性。",
        "초식성.",
        ["Long hind legs enable powerful jumps."]
    ),
}

def get_animals_by_category(category_id):
    return {k: v for k, v in ANIMALS_DATA.items() if v["category"] == category_id}

def get_animal_detail(animal_id):
    return ANIMALS_DATA.get(animal_id)
